name: Publish to Azure

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      envName:
        description: "The environment to deploy to (Staging or Production)"
        required: true
        default: "Staging"
        type: string
      envUrl:
        description: "The URL to deploy to"
        required: true
        default: "https://mona-dotnetweb-staging.azurewebsites.net/"
        type: string
      slotName:
        description: "The Azure Web App Slot to deploy to"
        retured: true
        default: "staging"
        type: string
    secrets:
      azureWebAppPublishProfile:
        required: true

jobs:
  deploy:
    
    name: Deploy to ${{ inputs.releaseType }}
    environment: 
      name: ${{ inputs.envName }}
      url: ${{ inputs.envUrl }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: env
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
      
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/dotnetweb 
        
    - name: 'Deploy to ${{ inputs.envName }} '
      uses: azure/webapps-deploy@v2
      with: 
        app-name: mona-dotnetweb
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: ${{env.DOTNET_ROOT}}/dotnetweb 
        slot-name: ${{ inputs.slotName }}